### step 1

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('../datasets/Data.csv')
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


### step 2

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [3]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

### Step 3: Handling the missing data

In [4]:
df.fillna(df.select_dtypes(include='number').mean(), inplace=True)

In [5]:
print(df)

   Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes


### split the data

In [6]:
X = df.iloc[ : ,:-1].values
y = df.iloc[: , 3].values

### Step 4: Encoding categorical data

In [10]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
labelencoder_X = LabelEncoder()
X[ : , 0]= labelencoder_X.fit_transform(X[: , 0])

In [2]:
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
    transformers=[("encoder", OneHotEncoder(), [0])],
    remainder="passthrough"
)

X = ct.fit_transform(X)

labelencoder_y = LabelEncoder()
y = labelencoder_Y.fit_transform(y)

NameError: name 'OneHotEncoder' is not defined

### Step 5: Splitting the datasets into training sets and Test sets

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

### Step 6: Feature Scaling


In [18]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

In [19]:
print(X_train)

[[-1.29099445  1.29099445 -0.77459667 -0.57735027  1.17419053  1.23812568]
 [ 0.77459667 -0.77459667  1.29099445 -0.57735027  1.43512176  1.58805718]
 [ 0.77459667 -0.77459667  1.29099445 -0.57735027 -1.17419053 -0.94894618]
 [-1.29099445  1.29099445 -0.77459667 -0.57735027  0.65232807  0.62574556]
 [ 0.77459667 -0.77459667  1.29099445 -0.57735027  0.13046561 -0.09355807]
 [ 0.77459667 -0.77459667 -0.77459667  1.73205081 -1.56558738 -1.47384342]
 [-1.29099445  1.29099445 -0.77459667 -0.57735027 -0.52186246 -0.59901468]
 [ 0.77459667 -0.77459667 -0.77459667  1.73205081 -0.13046561 -0.33656606]]


### DONE